# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Qtify

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies including missing babel plugin
        run: |
          npm install
          npm install --save-dev @babel/plugin-proposal-private-property-in-object

      - name: Run build script (if present)
        run: npm run build --if-present

      - name: Run tests with detectOpenHandles
        run: npm test -- --watchAll=false --detectOpenHandles

      - name: Upload artifact for deployment job
        if: success()  # Only upload artifacts if build & tests succeed
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read  # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B6861C0C870A4A0E848784FBB2C13A2B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E40A182FC5164213B1E8FFF473AE59B4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7F5B5AACAC824706B13EBD598F8B1449 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Qtify'
          slot-name: 'Production'
          package: .

          
